//CONSTANTES DE LA APLICACIÓN

export const ROLES = {
  ADMIN: "ADMIN",
  BIBLIOTECARIO: "BIBLIOTECARIO",
  SOCIO: "SOCIO",
};

export const ESTADO_SOLICITUD = {
  PENDIENTE: "PENDIENTE",
  APROBADA: "APROBADA",
  RECHAZADA: "RECHAZADA",
};

export const ESTADO_COPIA = {
  DISPONIBLE: "DISPONIBLE",
  PRESTADO: "PRESTADO",
};

export const FORMATO_COPIA = {
  FISICO: "FISICO",
  PDF: "PDF",
  EPUB: "EPUB",
  AUDIOBOOK: "AUDIOBOOK",
};

export const ESTADO_PRESTAMO = {
  ACTIVO: "ACTIVO",
  DEVUELTO: "DEVUELTO",
  VENCIDO: "VENCIDO",
  CANCELADO: "CANCELADO",
};

export const ESTADO_MULTA = {
  PENDIENTE: "PENDIENTE",
  PAGADA: "PAGADA",
  ANULADA: "ANULADA",
};

export const MULTA_TIPO = {
  DEVOLUCION_TARDIA: "DEVOLUCION_TARDIA",
  LIBRO_DANIADO: "LIBRO_DANIADO",
  LIBRO_PERDIDO: "LIBRO_PERDIDO",
};

export const MULTA_MONTOS = {
  [MULTA_TIPO.DEVOLUCION_TARDIA]: 1500,
  [MULTA_TIPO.LIBRO_DANIADO]: 8000,
  [MULTA_TIPO.LIBRO_PERDIDO]: 25000,
};

export const COLLECTIONS = {
  USUARIOS: "usuarios",
  SOCIOS: "socios",
  LIBROS: "libros",
  AUTORES: "autores",
  GENEROS: "generos",
  EDITORIALES: "editoriales",
  COPIAS: "copias",
  PRESTAMOS: "prestamos",
  MULTAS: "multas",
  SOLICITUDES: "solicitudes_registro",
  NOTIFICACIONES: "notificaciones",
  SESIONES: "sesiones",
};
